### ISSUE TITLE
Generating a URL works in V3 but not V4

### ISSUE THREAD

**Issue by tacman** [endroid/qr-code-bundle#50]
```twig
<img src="{{ qr_code_path('My QR Code') }}" />
<img src="{{ qr_code_url('My QR Code') }}" />
```

What is "My QR Code" in this context?  The twig functions do generate a QR code, but I'm confused on how to generate a QR code using the twig "path" or "url" functions.

Intuitively, it seems like a twig call like 

```twig
<img src="{{ qr_code_path('item_detail', {itemId: 123, mobile: true) }}" />
```

Would generate a QR code that, when scanned, would go to "https://example.com/123?mobile=true

I am almost positive this used to work, I found some code in an older project that seems 

```twig
    {% set url = url('item_show', {itemId: 123} ) %}
            <img height="150" src="{{ qr_code_url(url) }}" />
```

In fact, downgrading to v3 worked fine.  So it seems like something v4 should be able to support.  Thanks.

**Comment by endroid** [comment]
@tacman The qr_code_url did not handle URLs correctly. This should be fixed in 4.0.4.

**Comment by tacman** [comment]
In 4.0.4 it still doesn't encode the url parameters, just the domain name.

That is, https://ac.wip/qr-code/default/https://ac.wip/instance/goitia/Obj/datasheet/d2291d19-1646-49e2-8a91-43f8bbb4f8f9%3Fclean=1%26coreId=Obj

simply goes to https://ac.wip

![image](https://user-images.githubusercontent.com/619585/124355462-4b277880-dbdf-11eb-8b81-6041f030114e.png)

This worked in version 3.  That is 

```twig
            {% set absUrl = app.request.getSchemeAndHttpHost() ~ path('instance_datasheet', instance.irp({'clean': true})) %}
            <a target="_blank" href="{{ absUrl }}">
                <img class="float-left" alt="{{ instance.idno }} Datasheet" height="{{ height }}" src="{{ qr_code_url(absUrl) }}" />
            </a>
            <br/><small>{{ absUrl }}</small>
```

worked.

Any chance in v4 you could change the path function so that it mirrors the twig page?

 {{ path('route', {id: 123}) }}
 {{ qr_code_path('route', {id: 123}) }}

Thanks.

**Comment by tacman** [comment]
> @tacman The qr_code_url did not handle URLs correctly. This should be fixed in 4.0.4.

Do you mean that it will be fixed (in the future), or that it should be fixed now?

**Comment by endroid** [comment]
The qr_code_url (and path) method works like this: you just call the method and pass it any string data (in your case an URL but any string works). So you would have something like this.

    <img height="200" src="{{ qr_code_url('https://ac.wip/instance/goitia/Obj/datasheet/d2291d19-1646-49e2-8a91-43f8bbb4f8f9?clean=1&coreId=Obj') }}" />

When I put that in my template the qr_code_url method generates a valid QR code URL "https://my.domain/qr-code/default/https://ac.wip/instance/goitia/Obj/datasheet/d2291d19-1646-49e2-8a91-43f8bbb4f8f9%253Fclean=1%2526coreId=Obj" which renders as a valid QR code and after scanning returns the URL that was passed as data earlier. In other words, the generated URL seems OK here.

Have you also tried the qr_code_data_uri method? This immediately puts the QR code image data as a data URI in your template without creating a url or path for generating the QR code.

**Comment by tacman** [comment]
Yes, both are working.

My phone was asking me to go to the root domain, but another QR scanner
asks about the full path, so I was confused.

Anyway, yes, working as expected!

Thanks.
